# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-04 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_categorytopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
