# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-05 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160704_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorytopic',
            old_name='language',
            new_name='category',
        ),
    ]
