# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-05 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160704_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='language',
            new_name='name',
        ),
    ]
