# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-05 17:49
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160704_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='CategoryTopic', default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.CategoryTopic'),
        ),
    ]
